/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package xurxo.martinez.wordle.gui;

import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import xurxo.martinez.wordle.game.Colores;
import xurxo.martinez.wordle.game.WordleClass;
import xurxo.martinez.wordle.io.IMotorPalabras;
import xurxo.martinez.wordle.io.MotorTest;

/**
 *
 * @author xurxo
 */
public class PrincipalJForm extends javax.swing.JFrame {

    private static final Color VERDE = new Color(0, 102, 0);
    private static final Color AMARILLO = new Color(204, 153, 0);
    private static final Color ROJO = new Color(255, 51, 51);

    private static final int MAX_INTENTOS = 6;
    private static final int TAMANHO_PALABRA = 5;

    private final JLabel[][] labels = new JLabel[MAX_INTENTOS][TAMANHO_PALABRA];
    
    private IMotorPalabras motor = new MotorTest();
    private WordleClass game = new WordleClass();
    
    GestionMotorJDialog modalMotores = new GestionMotorJDialog(this, true);
    
    private String random = motor.getPalabraRandom().toUpperCase();
    private int intentos = 0;

    /**
     * Creates new form PrincipalJForm
     */
    public PrincipalJForm() {
        initComponents();
        inicializarLabels();
        resetGame();
    }

    public void resolver(List<Colores> col, String pal) {
        JLabel[] label = labels[intentos];
        for (int i = 0; i < label.length; i++) {
            JLabel jLabel = label[i];
            jLabel.setText(Character.toString(pal.charAt(i)));
            switch(col.get(i)){
                case VERDE:
                    jLabel.setForeground(VERDE);
                    break;
                case ROJO:
                    jLabel.setForeground(ROJO);
                    break;
                case AMARILLO:
                    jLabel.setForeground(AMARILLO);
                    break;
                default :
                    jLabel.setForeground(new Color(255, 255, 255));
                    break;
            }
            jLabel.setVisible(true);
            bienJLabel.setText(game.getBien());
            malJLabel.setText(game.getMal());
            existenJLabel.setText(game.getExiste());
        }
    }

    public final void resetGame() {
        game = new WordleClass();
        for (JLabel[] labelAr : labels) {
            for (JLabel jLabel : labelAr) {
                jLabel.setVisible(false);
            }
        }
        bienJLabel.setText("");
        malJLabel.setText("");
        existenJLabel.setText("");
        palabraJTextField.setText("");
        finalJLabel.setText("");
        errorJLabel.setText("");
    }
    
    public final void finGame() {
        JOptionPane.showMessageDialog(this, "Límite de intentos alcanzado, GAME OVER");
        resetGame();
    }
    
    public String getPalabraUsuario() {
        String pal = palabraJTextField.getText().toUpperCase();
        palabraJTextField.setText("");
        return pal;
    }
    
    public boolean checkPalabraUsuario() {
        if (!palabraJTextField.getText().matches("[A-Za-z]{5}")) {
            return false;
        } else {
            return true;
        }
    }
    
    public final void inicializarLabels() {
        for (int i = 1; i <= MAX_INTENTOS; i++) {
            for (int j = 1; j <= TAMANHO_PALABRA; j++) {
                try {
                    String nombreLabel = "JLabel" + i + "_" + j;
                    JLabel aux = (JLabel) this.getClass().getDeclaredField(nombreLabel).get(this);
                    labels[i - 1][j - 1] = aux;
                } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
                    Logger.getLogger(PrincipalJForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
      
    public IMotorPalabras getMotor() {
        return motor;
    }
    
    public void setMotor(IMotorPalabras newMotor) {
        motor = newMotor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainJPanel = new javax.swing.JPanel();
        letrasJPanel = new javax.swing.JPanel();
        JLabel1_1 = new javax.swing.JLabel();
        JLabel1_2 = new javax.swing.JLabel();
        JLabel1_3 = new javax.swing.JLabel();
        JLabel1_4 = new javax.swing.JLabel();
        JLabel1_5 = new javax.swing.JLabel();
        JLabel2_1 = new javax.swing.JLabel();
        JLabel2_2 = new javax.swing.JLabel();
        JLabel2_3 = new javax.swing.JLabel();
        JLabel2_4 = new javax.swing.JLabel();
        JLabel2_5 = new javax.swing.JLabel();
        JLabel3_1 = new javax.swing.JLabel();
        JLabel3_2 = new javax.swing.JLabel();
        JLabel3_3 = new javax.swing.JLabel();
        JLabel3_4 = new javax.swing.JLabel();
        JLabel3_5 = new javax.swing.JLabel();
        JLabel4_1 = new javax.swing.JLabel();
        JLabel4_2 = new javax.swing.JLabel();
        JLabel4_3 = new javax.swing.JLabel();
        JLabel4_4 = new javax.swing.JLabel();
        JLabel4_5 = new javax.swing.JLabel();
        JLabel5_1 = new javax.swing.JLabel();
        JLabel5_2 = new javax.swing.JLabel();
        JLabel5_3 = new javax.swing.JLabel();
        JLabel5_4 = new javax.swing.JLabel();
        JLabel5_5 = new javax.swing.JLabel();
        JLabel6_1 = new javax.swing.JLabel();
        JLabel6_2 = new javax.swing.JLabel();
        JLabel6_3 = new javax.swing.JLabel();
        JLabel6_4 = new javax.swing.JLabel();
        JLabel6_5 = new javax.swing.JLabel();
        controlJPanel = new javax.swing.JPanel();
        estadoJPanel = new javax.swing.JPanel();
        malJPanel = new javax.swing.JPanel();
        malJLabel = new javax.swing.JLabel();
        existenJPanel = new javax.swing.JPanel();
        existenJLabel = new javax.swing.JLabel();
        bienJPanel = new javax.swing.JPanel();
        bienJLabel = new javax.swing.JLabel();
        entradaJPanel = new javax.swing.JPanel();
        palabraJTextField = new javax.swing.JTextField();
        enviarJButton = new javax.swing.JButton();
        exitoJPanel = new javax.swing.JPanel();
        finalJLabel = new javax.swing.JLabel();
        errorJPanel = new javax.swing.JPanel();
        errorJLabel = new javax.swing.JLabel();
        menuJmenuBar = new javax.swing.JMenuBar();
        archivoJMenu = new javax.swing.JMenu();
        nuevaPartidaJMenuItem = new javax.swing.JMenuItem();
        motoresJMenu = new javax.swing.JMenu();
        listaMotoresJMenu = new javax.swing.JMenu();
        motorTestJMenuItem = new javax.swing.JMenuItem();
        gestionMotorJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xurxo Martínez Ferreira");

        mainJPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainJPanel.setPreferredSize(new java.awt.Dimension(500, 600));
        mainJPanel.setRequestFocusEnabled(false);
        mainJPanel.setLayout(new java.awt.BorderLayout());

        letrasJPanel.setBackground(new java.awt.Color(204, 204, 204));
        letrasJPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        letrasJPanel.setLayout(new java.awt.GridLayout(6, 5));

        JLabel1_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_1.setText("A");
        letrasJPanel.add(JLabel1_1);

        JLabel1_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_2.setText("A");
        letrasJPanel.add(JLabel1_2);

        JLabel1_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_3.setText("A");
        letrasJPanel.add(JLabel1_3);

        JLabel1_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_4.setText("A");
        letrasJPanel.add(JLabel1_4);

        JLabel1_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel1_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel1_5.setText("A");
        letrasJPanel.add(JLabel1_5);

        JLabel2_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_1.setText("A");
        letrasJPanel.add(JLabel2_1);

        JLabel2_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_2.setText("A");
        letrasJPanel.add(JLabel2_2);

        JLabel2_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_3.setText("A");
        letrasJPanel.add(JLabel2_3);

        JLabel2_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_4.setText("A");
        letrasJPanel.add(JLabel2_4);

        JLabel2_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel2_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel2_5.setText("A");
        letrasJPanel.add(JLabel2_5);

        JLabel3_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_1.setText("A");
        letrasJPanel.add(JLabel3_1);

        JLabel3_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_2.setText("A");
        letrasJPanel.add(JLabel3_2);

        JLabel3_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_3.setText("A");
        letrasJPanel.add(JLabel3_3);

        JLabel3_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_4.setText("A");
        letrasJPanel.add(JLabel3_4);

        JLabel3_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel3_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel3_5.setText("A");
        letrasJPanel.add(JLabel3_5);

        JLabel4_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_1.setText("A");
        letrasJPanel.add(JLabel4_1);

        JLabel4_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_2.setText("A");
        letrasJPanel.add(JLabel4_2);

        JLabel4_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_3.setText("A");
        letrasJPanel.add(JLabel4_3);

        JLabel4_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_4.setText("A");
        letrasJPanel.add(JLabel4_4);

        JLabel4_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel4_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel4_5.setText("A");
        letrasJPanel.add(JLabel4_5);

        JLabel5_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_1.setText("A");
        letrasJPanel.add(JLabel5_1);

        JLabel5_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_2.setText("A");
        letrasJPanel.add(JLabel5_2);

        JLabel5_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_3.setText("A");
        letrasJPanel.add(JLabel5_3);

        JLabel5_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_4.setText("A");
        letrasJPanel.add(JLabel5_4);

        JLabel5_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel5_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel5_5.setText("A");
        letrasJPanel.add(JLabel5_5);

        JLabel6_1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel6_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel6_1.setText("A");
        letrasJPanel.add(JLabel6_1);

        JLabel6_2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel6_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel6_2.setText("A");
        letrasJPanel.add(JLabel6_2);

        JLabel6_3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel6_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel6_3.setText("A");
        letrasJPanel.add(JLabel6_3);

        JLabel6_4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel6_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel6_4.setText("A");
        letrasJPanel.add(JLabel6_4);

        JLabel6_5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        JLabel6_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel6_5.setText("A");
        letrasJPanel.add(JLabel6_5);

        mainJPanel.add(letrasJPanel, java.awt.BorderLayout.CENTER);

        controlJPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        controlJPanel.setLayout(new java.awt.GridLayout(2, 2));

        estadoJPanel.setBackground(new java.awt.Color(204, 204, 204));
        estadoJPanel.setLayout(new java.awt.GridLayout(3, 1));

        malJPanel.setBackground(new java.awt.Color(204, 204, 204));
        malJPanel.setLayout(new java.awt.GridLayout(1, 0));

        malJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        malJLabel.setForeground(new java.awt.Color(255, 51, 51));
        malJPanel.add(malJLabel);

        estadoJPanel.add(malJPanel);

        existenJPanel.setBackground(new java.awt.Color(204, 204, 204));
        existenJPanel.setLayout(new java.awt.GridLayout(1, 0));

        existenJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        existenJLabel.setForeground(new java.awt.Color(204, 153, 0));
        existenJPanel.add(existenJLabel);

        estadoJPanel.add(existenJPanel);

        bienJPanel.setBackground(new java.awt.Color(204, 204, 204));
        bienJPanel.setLayout(new java.awt.GridLayout(1, 0));

        bienJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bienJLabel.setForeground(new java.awt.Color(0, 102, 0));
        bienJPanel.add(bienJLabel);

        estadoJPanel.add(bienJPanel);

        controlJPanel.add(estadoJPanel);

        entradaJPanel.setBackground(new java.awt.Color(204, 204, 204));

        palabraJTextField.setPreferredSize(new java.awt.Dimension(150, 24));
        entradaJPanel.add(palabraJTextField);

        enviarJButton.setText("Enviar");
        enviarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarJButtonActionPerformed(evt);
            }
        });
        entradaJPanel.add(enviarJButton);

        controlJPanel.add(entradaJPanel);

        exitoJPanel.setBackground(new java.awt.Color(204, 204, 204));
        exitoJPanel.setLayout(new java.awt.GridBagLayout());

        finalJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        finalJLabel.setForeground(new java.awt.Color(0, 102, 0));
        finalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitoJPanel.add(finalJLabel, new java.awt.GridBagConstraints());

        controlJPanel.add(exitoJPanel);

        errorJPanel.setBackground(new java.awt.Color(204, 204, 204));
        errorJPanel.setLayout(new java.awt.GridBagLayout());

        errorJLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errorJLabel.setForeground(new java.awt.Color(255, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 104, 21, 105);
        errorJPanel.add(errorJLabel, gridBagConstraints);

        controlJPanel.add(errorJPanel);

        mainJPanel.add(controlJPanel, java.awt.BorderLayout.PAGE_END);

        menuJmenuBar.setBackground(new java.awt.Color(204, 204, 204));

        archivoJMenu.setText("Archivo");

        nuevaPartidaJMenuItem.setText("Nueva partida");
        archivoJMenu.add(nuevaPartidaJMenuItem);

        menuJmenuBar.add(archivoJMenu);

        motoresJMenu.setText("Motores");

        listaMotoresJMenu.setText("Cambiar motor");
        listaMotoresJMenu.setToolTipText("");

        motorTestJMenuItem.setText("Motor test");
        listaMotoresJMenu.add(motorTestJMenuItem);

        motoresJMenu.add(listaMotoresJMenu);

        gestionMotorJMenuItem.setText("Gestion motor");
        motoresJMenu.add(gestionMotorJMenuItem);

        menuJmenuBar.add(motoresJMenu);

        setJMenuBar(menuJmenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarJButtonActionPerformed
        String usuario;
        if (checkPalabraUsuario()) {
            usuario = getPalabraUsuario();
            List<Colores> colores = game.comprobarPalabra(random, usuario);
            resolver(colores, usuario);
            intentos++;
            if (intentos >= 6) {
                finGame();
            }
        } else {
            errorJLabel.setText("La palabra no cumple el formato AAAAA!");
            palabraJTextField.setText("");
        }
    }//GEN-LAST:event_enviarJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1_1;
    private javax.swing.JLabel JLabel1_2;
    private javax.swing.JLabel JLabel1_3;
    private javax.swing.JLabel JLabel1_4;
    private javax.swing.JLabel JLabel1_5;
    private javax.swing.JLabel JLabel2_1;
    private javax.swing.JLabel JLabel2_2;
    private javax.swing.JLabel JLabel2_3;
    private javax.swing.JLabel JLabel2_4;
    private javax.swing.JLabel JLabel2_5;
    private javax.swing.JLabel JLabel3_1;
    private javax.swing.JLabel JLabel3_2;
    private javax.swing.JLabel JLabel3_3;
    private javax.swing.JLabel JLabel3_4;
    private javax.swing.JLabel JLabel3_5;
    private javax.swing.JLabel JLabel4_1;
    private javax.swing.JLabel JLabel4_2;
    private javax.swing.JLabel JLabel4_3;
    private javax.swing.JLabel JLabel4_4;
    private javax.swing.JLabel JLabel4_5;
    private javax.swing.JLabel JLabel5_1;
    private javax.swing.JLabel JLabel5_2;
    private javax.swing.JLabel JLabel5_3;
    private javax.swing.JLabel JLabel5_4;
    private javax.swing.JLabel JLabel5_5;
    private javax.swing.JLabel JLabel6_1;
    private javax.swing.JLabel JLabel6_2;
    private javax.swing.JLabel JLabel6_3;
    private javax.swing.JLabel JLabel6_4;
    private javax.swing.JLabel JLabel6_5;
    private javax.swing.JMenu archivoJMenu;
    private javax.swing.JLabel bienJLabel;
    private javax.swing.JPanel bienJPanel;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JPanel entradaJPanel;
    private javax.swing.JButton enviarJButton;
    private javax.swing.JLabel errorJLabel;
    private javax.swing.JPanel errorJPanel;
    private javax.swing.JPanel estadoJPanel;
    private javax.swing.JLabel existenJLabel;
    private javax.swing.JPanel existenJPanel;
    private javax.swing.JPanel exitoJPanel;
    private javax.swing.JLabel finalJLabel;
    private javax.swing.JMenuItem gestionMotorJMenuItem;
    private javax.swing.JPanel letrasJPanel;
    private javax.swing.JMenu listaMotoresJMenu;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JLabel malJLabel;
    private javax.swing.JPanel malJPanel;
    private javax.swing.JMenuBar menuJmenuBar;
    private javax.swing.JMenuItem motorTestJMenuItem;
    private javax.swing.JMenu motoresJMenu;
    private javax.swing.JMenuItem nuevaPartidaJMenuItem;
    private javax.swing.JTextField palabraJTextField;
    // End of variables declaration//GEN-END:variables
}
